channels:
  - conda-forge
dependencies:
  - python=3.11 # You can adjust the Python version if needed
  - pip
  - pip:
      - rpaframework
      - yfinance
      - requests
      - textblob
      - robocorp
      - pytz
      - boto3
